on: push

jobs:
  CodeQL-ML-job:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: CodeQL-ML
      uses: ai-revise/codeql-ml@v1.1.1
      with:
       workspace: ${{ github.workspace }}

